# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ansible"

  config.vm.define "ansible" do |control|
    control.vm.network :private_network, ip: "192.168.61.10"
    control.vm.hostname  = "ansible"
    control.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "384"]
    end
  end

  config.vm.define "db" do |db|
    db.vm.network :private_network, ip: "192.168.61.11"
    db.vm.hostname  = "db"
    db.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "512"]
    end
  end

  config.vm.define "app1" do |app|
    app.vm.network :private_network, ip: "192.168.61.12"
    app.vm.hostname = "app1"
    app.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "384"]
    end
  end

  config.vm.define "app2" do |app|
    app.vm.network :private_network, ip: "192.168.61.13"
    app.vm.hostname = "app2"
    app.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "384"]
    end
  end


  config.vm.define "lb" do |lb|
    lb.vm.network :private_network, ip: "192.168.61.14"
    lb.vm.hostname  = "lb"
    lb.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "256"]
    end
  end

  config.vm.provision "shell", inline: <<-SHELL
    mkdir -p /etc/yum.repos.d/repo.bkp && mv /etc/yum.repos.d/*.repo /etc/yum.repos.d/repo.bkp/ && mv /etc/yum.repos.d/repo.bkp/local_* /etc/yum.repos.d/
  SHELL

end
